# Docker-compose version.
version: '3'

# The list of services (containers): NGINX, PHP, MySQL
services:
  nginx:
      build:
          context: .
          dockerfile: docker/Nginx.Dockerfile
      ports:
          - 8098:80
      links:
          - fpm
      volumes:
        - ./:/var/www/laravel-docker
  fpm:
      build:
        context: .
        dockerfile: docker/Fpm.Dockerfile
      volumes:
        - ./:/var/www/laravel-docker
      links:
        - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=200384
      - MYSQL_DATABASE=sitemanufactura
